name: Build ChimeraOS Installer

on:
  push:
    branches:
      - main
    tags: '*'
  workflow_dispatch:

jobs:
  build-installer:
    name: Build Graphical Installer
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3
      - name: Set up pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm unzip godot wget git fontconfig
      - name: Build ChimeraOS installer
        id: build
        shell: bash
        run: |
          godot --version
          make build
      - name: Upload package artifact
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v3
        with:
          name: chimeraos-installer
          path: |
            build/chimeraos-installer.x86_64
          if-no-files-found: error

  make-release:
    name: Release
    runs-on: ubuntu-latest
    needs: build-installer
    if: github.ref_type == 'tag'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: chimeraos-installer
          path: '.'
      - name: Test
        run: |
          ls -ahl
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: ChimeraOS installer
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            chimera-installer.x86_64